In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("online_sales.csv")
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Discount,PaymentMethod,ShippingCost,Category,SalesChannel,ReturnStatus,ShipmentProvider,WarehouseLocation,OrderPriority
0,221958,SKU_1964,White Mug,38,2020-01-01 00:00,1.71,37039.0,Australia,0.470000,Bank Transfer,10.79,Apparel,In-store,Not Returned,UPS,London,Medium
1,771155,SKU_1241,White Mug,18,2020-01-01 01:00,41.25,19144.0,Spain,0.190000,paypall,9.51,Electronics,Online,Not Returned,UPS,Rome,Medium
2,231932,SKU_1501,Headphones,49,2020-01-01 02:00,29.11,50472.0,Germany,0.350000,Bank Transfer,23.03,Electronics,Online,Returned,UPS,Berlin,High
3,465838,SKU_1760,Desk Lamp,14,2020-01-01 03:00,76.68,96586.0,Netherlands,0.140000,paypall,11.08,Accessories,Online,Not Returned,Royal Mail,Rome,Low
4,359178,SKU_1386,USB Cable,-30,2020-01-01 04:00,-68.11,NaN,United Kingdom,1.501433,Bank Transfer,NaN,Electronics,In-store,Not Returned,FedEx,NaN,Medium

In [3]:
df.tail()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Discount,PaymentMethod,ShippingCost,Category,SalesChannel,ReturnStatus,ShipmentProvider,WarehouseLocation,OrderPriority
49777,354083,SKU_1562,Blue Pen,25,2025-09-05 01:00,70.92,51445.0,Spain,0.20,Credit Card,8.96,Electronics,Online,Returned,UPS,Berlin,Medium
49778,296698,SKU_1930,USB Cable,7,2025-09-05 02:00,51.74,28879.0,United States,0.23,Bank Transfer,23.55,Electronics,Online,Not Returned,FedEx,Amsterdam,Low
49779,177622,SKU_1766,Office Chair,43,2025-09-05 03:00,85.25,21825.0,Portugal,0.20,Bank Transfer,16.26,Furniture,In-store,Not Returned,FedEx,London,High
49780,701213,SKU_1602,Notebook,48,2025-09-05 04:00,39.64,43199.0,United Kingdom,0.31,paypall,28.56,Apparel,Online,Not Returned,Royal Mail,London,Medium
49781,772215,SKU_1832,White Mug,30,2025-09-05 05:00,38.27,53328.0,France,0.10,Credit Card,9.13,Stationery,Online,Not Returned,UPS,Rome,Low

In [4]:
print(df.info())
print(df.shape)
print(df.describe())
print(df.columns)
df.columns = df.columns.str.strip()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49782 entries, 0 to 49781
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   InvoiceNo          49782 non-null  int64
 1   StockCode          49782 non-null  object
 2   Description        49782 non-null  object
 3   Quantity           49782 non-null  int64
 4   InvoiceDate        49782 non-null  object
 5   UnitPrice          49782 non-null  float64
 6   CustomerID         44804 non-null  float64
 7   Country            49782 non-null  object
 8   Discount           49782 non-null  float64
 9   PaymentMethod      49782 non-null  object
 10  ShippingCost       47293 non-null  float64
 11  Category           49782 non-null  object
 12  SalesChannel       49782 non-null  object
 13  ReturnStatus       49782 non-null  object
 14  ShipmentProvider   49782 non-null  object
 15  WarehouseLocation  46297 non-null  object
 16  OrderPriority      49782 non-null  object
dtypes: float64(4), int64(2), object(11)
memory usage: 6.5+ MB
None
(49782, 17)
           InvoiceNo      Quantity     UnitPrice    CustomerID      Discount  \
count   49782.000000  49782.000000  49782.000000  44804.000000  49782.000000
mean   550681.239946     22.372343     47.537862  55032.871775      0.275748
std    260703.009944     17.917774     33.479510  25913.660157      0.230077
min    100005.000000    -50.000000    -99.980000  10001.000000      0.000000
25%    324543.000000     11.000000     23.592500  32750.750000      0.130000
50%    552244.000000     23.000000     48.920000  55165.000000      0.260000
75%    776364.000000     37.000000     74.610000  77306.250000      0.380000
max    999997.000000     49.000000    100.000000  99998.000000      1.999764

       ShippingCost
count  47293.000000
mean      17.494529
std        7.220557
min        5.000000
25%       11.220000
50%       17.500000
75%       23.720000
max       30.000000
Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country', 'Discount', 'PaymentMethod',
       'ShippingCost', 'Category', 'SalesChannel', 'ReturnStatus',
       'ShipmentProvider', 'WarehouseLocation', 'OrderPriority'],
      dtype='object')

In [5]:
df.drop_duplicates()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Discount,PaymentMethod,ShippingCost,Category,SalesChannel,ReturnStatus,ShipmentProvider,WarehouseLocation,OrderPriority
0,221958,SKU_1964,White Mug,38,2020-01-01 00:00,1.71,37039.0,Australia,0.470000,Bank Transfer,10.79,Apparel,In-store,Not Returned,UPS,London,Medium
1,771155,SKU_1241,White Mug,18,2020-01-01 01:00,41.25,19144.0,Spain,0.190000,paypall,9.51,Electronics,Online,Not Returned,UPS,Rome,Medium
2,231932,SKU_1501,Headphones,49,2020-01-01 02:00,29.11,50472.0,Germany,0.350000,Bank Transfer,23.03,Electronics,Online,Returned,UPS,Berlin,High
3,465838,SKU_1760,Desk Lamp,14,2020-01-01 03:00,76.68,96586.0,Netherlands,0.140000,paypall,11.08,Accessories,Online,Not Returned,Royal Mail,Rome,Low
4,359178,SKU_1386,USB Cable,-30,2020-01-01 04:00,-68.11,NaN,United Kingdom,1.501433,Bank Transfer,NaN,Electronics,In-store,Not Returned,FedEx,NaN,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49777,354083,SKU_1562,Blue Pen,25,2025-09-05 01:00,70.92,51445.0,Spain,0.200000,Credit Card,8.96,Electronics,Online,Returned,UPS,Berlin,Medium
49778,296698,SKU_1930,USB Cable,7,2025-09-05 02:00,51.74,28879.0,United States,0.230000,Bank Transfer,23.55,Electronics,Online,Not Returned,FedEx,Amsterdam,Low
49779,177622,SKU_1766,Office Chair,43,2025-09-05 03:00,85.25,21825.0,Portugal,0.200000,Bank Transfer,16.26,Furniture,In-store,Not Returned,FedEx,London,High
49780,701213,SKU_1602,Notebook,48,2025-09-05 04:00,39.64,43199.0,United Kingdom,0.310000,paypall,28.56,Apparel,Online,Not Returned,Royal Mail,London,Medium
49781,772215,SKU_1832,White Mug,30,2025-09-05 05:00,38.27,53328.0,France,0.100000,Credit Card,9.13,Stationery,Online,Not Returned,UPS,Rome,Low

In [6]:
df.isnull().sum()

InvoiceNo               0
StockCode               0
Description             0
Quantity                0
InvoiceDate             0
UnitPrice               0
CustomerID           4978
Country                 0
Discount                0
PaymentMethod           0
ShippingCost         2489
Category                0
SalesChannel            0
ReturnStatus            0
ShipmentProvider        0
WarehouseLocation    3485
OrderPriority           0
dtype: int64

In [7]:
# Handle CustomerID
df['CustomerID'].fillna('Annoymous', inplace=True)
# Handle WarehouseLocation 
df['WarehouseLocation'].fillna('Unknown', inplace=True)
# Set Shipping Cost to 0 where SalesChannel is "In-store" due to their beginning no shipping cost
df.loc[df['SalesChannel'] == 'In-store', 'ShippingCost'] = 0

In [8]:
df.head(10)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Discount,PaymentMethod,ShippingCost,Category,SalesChannel,ReturnStatus,ShipmentProvider,WarehouseLocation,OrderPriority
0,221958,SKU_1964,White Mug,38,2020-01-01 00:00,1.71,37039.0,Australia,0.470000,Bank Transfer,0.00,Apparel,In-store,Not Returned,UPS,London,Medium
1,771155,SKU_1241,White Mug,18,2020-01-01 01:00,41.25,19144.0,Spain,0.190000,paypall,9.51,Electronics,Online,Not Returned,UPS,Rome,Medium
2,231932,SKU_1501,Headphones,49,2020-01-01 02:00,29.11,50472.0,Germany,0.350000,Bank Transfer,23.03,Electronics,Online,Returned,UPS,Berlin,High
3,465838,SKU_1760,Desk Lamp,14,2020-01-01 03:00,76.68,96586.0,Netherlands,0.140000,paypall,11.08,Accessories,Online,Not Returned,Royal Mail,Rome,Low
4,359178,SKU_1386,USB Cable,-30,2020-01-01 04:00,-68.11,Annoymous,United Kingdom,1.501433,Bank Transfer,0.00,Electronics,In-store,Not Returned,FedEx,Unknown,Medium
5,744167,SKU_1006,Office Chair,47,2020-01-01 05:00,70.16,53887.0,Sweden,0.480000,Credit Card,13.98,Electronics,Online,Not Returned,DHL,London,Medium
6,210268,SKU_1087,USB Cable,25,2020-01-01 06:00,85.74,46567.0,Belgium,0.150000,Bank Transfer,12.92,Stationery,Online,Not Returned,FedEx,Amsterdam,High
7,832180,SKU_1597,Notebook,8,2020-01-01 07:00,95.65,75098.0,Norway,0.040000,Bank Transfer,0.00,Electronics,In-store,Not Returned,Royal Mail,Amsterdam,Low
8,154886,SKU_1907,Wireless Mouse,19,2020-01-01 08:00,98.19,87950.0,Belgium,0.050000,paypall,12.56,Apparel,Online,Not Returned,UPS,Berlin,High
9,237337,SKU_1866,Headphones,40,2020-01-01 09:00,98.17,39718.0,Italy,0.160000,Bank Transfer,7.71,Apparel,Online,Not Returned,Royal Mail,London,Low

In [9]:
# Drop rows with NaN values:
df.dropna(inplace=True)

In [10]:
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'], errors = 'coerce')

In [11]:
# List of columns to convert to categorical type
categorical_columns = ['PaymentMethod', 'Country', 'Category', 'SalesChannel', 'OrderPriority', 'ReturnStatus', 'ShipmentProvider', 'WarehouseLocation']

# Convert all listed columns to 'category' dtype
df[categorical_columns] = df[categorical_columns].apply(lambda x: x.astype('category'))
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Discount,PaymentMethod,ShippingCost,Category,SalesChannel,ReturnStatus,ShipmentProvider,WarehouseLocation,OrderPriority
0,221958,SKU_1964,White Mug,38,2020-01-01 00:00:00,1.71,37039.0,Australia,0.470000,Bank Transfer,0.00,Apparel,In-store,Not Returned,UPS,London,Medium
1,771155,SKU_1241,White Mug,18,2020-01-01 01:00:00,41.25,19144.0,Spain,0.190000,paypall,9.51,Electronics,Online,Not Returned,UPS,Rome,Medium
2,231932,SKU_1501,Headphones,49,2020-01-01 02:00:00,29.11,50472.0,Germany,0.350000,Bank Transfer,23.03,Electronics,Online,Returned,UPS,Berlin,High
3,465838,SKU_1760,Desk Lamp,14,2020-01-01 03:00:00,76.68,96586.0,Netherlands,0.140000,paypall,11.08,Accessories,Online,Not Returned,Royal Mail,Rome,Low
4,359178,SKU_1386,USB Cable,-30,2020-01-01 04:00:00,-68.11,Annoymous,United Kingdom,1.501433,Bank Transfer,0.00,Electronics,In-store,Not Returned,FedEx,Unknown,Medium

In [12]:
import numpy as np

# Calculate TotalPrice and round it up
df['TotalPrice'] = df.apply(
    lambda row: np.ceil(row['Quantity'] * row['UnitPrice']) if row['ReturnStatus'] != 'Returned' 
    else -np.ceil(row['Quantity'] * row['UnitPrice']), axis=1
)

In [13]:
df.head(20)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Discount,PaymentMethod,ShippingCost,Category,SalesChannel,ReturnStatus,ShipmentProvider,WarehouseLocation,OrderPriority,TotalPrice
0,221958,SKU_1964,White Mug,38,2020-01-01 00:00:00,1.71,37039.0,Australia,0.470000,Bank Transfer,0.00,Apparel,In-store,Not Returned,UPS,London,Medium,65.0
1,771155,SKU_1241,White Mug,18,2020-01-01 01:00:00,41.25,19144.0,Spain,0.190000,paypall,9.51,Electronics,Online,Not Returned,UPS,Rome,Medium,743.0
2,231932,SKU_1501,Headphones,49,2020-01-01 02:00:00,29.11,50472.0,Germany,0.350000,Bank Transfer,23.03,Electronics,Online,Returned,UPS,Berlin,High,-1427.0
3,465838,SKU_1760,Desk Lamp,14,2020-01-01 03:00:00,76.68,96586.0,Netherlands,0.140000,paypall,11.08,Accessories,Online,Not Returned,Royal Mail,Rome,Low,1074.0
4,359178,SKU_1386,USB Cable,-30,2020-01-01 04:00:00,-68.11,Annoymous,United Kingdom,1.501433,Bank Transfer,0.00,Electronics,In-store,Not Returned,FedEx,Unknown,Medium,2044.0
5,744167,SKU_1006,Office Chair,47,2020-01-01 05:00:00,70.16,53887.0,Sweden,0.480000,Credit Card,13.98,Electronics,Online,Not Returned,DHL,London,Medium,3298.0
6,210268,SKU_1087,USB Cable,25,2020-01-01 06:00:00,85.74,46567.0,Belgium,0.150000,Bank Transfer,12.92,Stationery,Online,Not Returned,FedEx,Amsterdam,High,2144.0
7,832180,SKU_1597,Notebook,8,2020-01-01 07:00:00,95.65,75098.0,Norway,0.040000,Bank Transfer,0.00,Electronics,In-store,Not Returned,Royal Mail,Amsterdam,Low,766.0
8,154886,SKU_1907,Wireless Mouse,19,2020-01-01 08:00:00,98.19,87950.0,Belgium,0.050000,paypall,12.56,Apparel,Online,Not Returned,UPS,Berlin,High,1866.0
9,237337,SKU_1866,Headphones,40,2020-01-01 09:00:00,98.17,39718.0,Italy,0.160000,Bank Transfer,7.71,Apparel,Online,Not Returned,Royal Mail,London,Low,3927.0
10,621430,SKU_1144,Notebook,49,2020-01-01 10:00:00,87.56,13030.0,United Kingdom,0.190000,paypall,0.00,Stationery,In-store,Returned,UPS,Paris,Medium,-4291.0
11,187498,SKU_1450,Office Chair,41,2020-01-01 11:00:00,59.51,32466.0,Australia,0.390000,Bank Transfer,0.00,Furniture,In-store,Not Returned,FedEx,Amsterdam,Low,2440.0
12,999159,SKU_1330,Blue Pen,41,2020-01-01 12:00:00,25.59,89794.0,Australia,0.010000,Credit Card,0.00,Electronics,In-store,Not Returned,FedEx,Berlin,Medium,1050.0
13,275203,SKU_1709,Headphones,3,2020-01-01 13:00:00,2.09,97817.0,Spain,0.470000,Credit Card,19.22,Stationery,Online,Not Returned,Royal Mail,Paris,Low,7.0
14,291335,SKU_1874,Wall Clock,29,2020-01-01 14:00:00,35.88,43017.0,Portugal,0.060000,Credit Card,14.85,Electronics,Online,Not Returned,Royal Mail,Amsterdam,High,1041.0
15,378167,SKU_1163,T-shirt,16,2020-01-01 15:00:00,82.58,85852.0,Belgium,0.410000,Bank Transfer,0.00,Furniture,In-store,Not Returned,UPS,Amsterdam,High,1322.0
16,141090,SKU_1656,Office Chair,7,2020-01-01 16:00:00,70.85,15473.0,Germany,0.000000,Bank Transfer,0.00,Apparel,In-store,Not Returned,FedEx,Paris,High,496.0
17,429365,SKU_1341,Headphones,49,2020-01-01 17:00:00,14.91,55644.0,Netherlands,0.360000,Bank Transfer,5.32,Stationery,Online,Not Returned,Royal Mail,Paris,Medium,731.0
18,164820,SKU_1000,Backpack,21,2020-01-01 18:00:00,1.07,20566.0,Sweden,0.490000,Bank Transfer,15.09,Accessories,Online,Not Returned,FedEx,London,Medium,23.0
19,887201,SKU_1119,USB Cable,46,2020-01-01 19:00:00,27.03,19819.0,Spain,0.260000,Credit Card,0.00,Furniture,In-store,Returned,UPS,London,Medium,-1244.0

In [14]:
print(df.info())
print(df.describe())

<class 'pandas.core.frame.DataFrame'>
Index: 48493 entries, 0 to 49781
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   InvoiceNo          48493 non-null  int64
 1   StockCode          48493 non-null  object
 2   Description        48493 non-null  object
 3   Quantity           48493 non-null  int64
 4   InvoiceDate        48493 non-null  datetime64[ns]
 5   UnitPrice          48493 non-null  float64
 6   CustomerID         48493 non-null  object
 7   Country            48493 non-null  category
 8   Discount           48493 non-null  float64
 9   PaymentMethod      48493 non-null  category
 10  ShippingCost       48493 non-null  float64
 11  Category           48493 non-null  category
 12  SalesChannel       48493 non-null  category
 13  ReturnStatus       48493 non-null  category
 14  ShipmentProvider   48493 non-null  category
 15  WarehouseLocation  48493 non-null  category
 16  OrderPriority      48493 non-null  category
 17  TotalPrice         48493 non-null  float64
dtypes: category(8), datetime64[ns](1), float64(4), int64(2), object(3)
memory usage: 4.4+ MB
None
           InvoiceNo      Quantity                    InvoiceDate  \
count   48493.000000  48493.000000                          48493
mean   550209.678861     23.653373  2022-11-02 11:20:03.761367296
min    100005.000000    -50.000000            2020-01-01 00:00:00
25%    324237.000000     12.000000            2021-06-02 10:00:00
50%    551598.000000     24.000000            2022-11-02 00:00:00
75%    775748.000000     37.000000            2024-04-03 13:00:00
max    999997.000000     49.000000            2025-09-05 05:00:00
std    260618.177031     16.146156                            NaN

          UnitPrice      Discount  ShippingCost    TotalPrice
count  48493.000000  48493.000000  48493.000000  48493.000000
mean      49.060792      0.263130      8.553452    993.632566
min      -99.860000      0.000000      0.000000  -4872.000000
25%       24.750000      0.130000      0.000000    212.000000
50%       49.610000      0.250000      0.000000    789.000000
75%       75.040000      0.380000     17.210000   1764.000000
max      100.000000      1.998946     30.000000   4925.000000
std       31.180515      0.192679     10.079885   1334.837568

In [15]:
df = df[df['Quantity'] >= 0]

# Step 2: Adjust TotalPrice calculation based on ReturnStatus
df['TotalPrice'] = df.apply(
    lambda row: row['Quantity'] * row['UnitPrice'] if row['ReturnStatus'] != 'Returned' else -row['Quantity'] * row['UnitPrice'], axis=1
)
print(df.head())

   InvoiceNo StockCode   Description  Quantity         InvoiceDate  UnitPrice  \
0     221958  SKU_1964     White Mug        38 2020-01-01 00:00:00       1.71
1     771155  SKU_1241     White Mug        18 2020-01-01 01:00:00      41.25
2     231932  SKU_1501    Headphones        49 2020-01-01 02:00:00      29.11
3     465838  SKU_1760     Desk Lamp        14 2020-01-01 03:00:00      76.68
5     744167  SKU_1006  Office Chair        47 2020-01-01 05:00:00      70.16

  CustomerID      Country  Discount  PaymentMethod  ShippingCost     Category  \
0    37039.0    Australia      0.47  Bank Transfer          0.00      Apparel
1    19144.0        Spain      0.19        paypall          9.51  Electronics
2    50472.0      Germany      0.35  Bank Transfer         23.03  Electronics
3    96586.0  Netherlands      0.14        paypall         11.08  Accessories
5    53887.0       Sweden      0.48    Credit Card         13.98  Electronics

  SalesChannel  ReturnStatus ShipmentProvider WarehouseLocation OrderPriority  \
0     In-store  Not Returned              UPS            London        Medium
1       Online  Not Returned              UPS              Rome        Medium
2       Online      Returned              UPS            Berlin          High
3       Online  Not Returned       Royal Mail              Rome           Low
5       Online  Not Returned              DHL            London        Medium

   TotalPrice
0       64.98
1      742.50
2    -1426.39
3     1073.52
5     3297.52

In [16]:
# Count the number of discounts greater than 1 without returns
discounts_above_1_no_returns = df[(df['Discount'] > 1) & (df['ReturnStatus'] != 'Returned')]
count_above_1_no_returns = len(discounts_above_1_no_returns)

print(f"Number of discounts greater than 1 without returns: {count_above_1_no_returns}")

# Check if all discounts > 1 are returns
all_discounts_above_1_are_returns = (df[df['Discount'] > 1]['ReturnStatus'].eq('Returned').all())

Number of discounts greater than 1 without returns: 0

In [17]:
df.head(10)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Discount,PaymentMethod,ShippingCost,Category,SalesChannel,ReturnStatus,ShipmentProvider,WarehouseLocation,OrderPriority,TotalPrice
0,221958,SKU_1964,White Mug,38,2020-01-01 00:00:00,1.71,37039.0,Australia,0.47,Bank Transfer,0.00,Apparel,In-store,Not Returned,UPS,London,Medium,64.98
1,771155,SKU_1241,White Mug,18,2020-01-01 01:00:00,41.25,19144.0,Spain,0.19,paypall,9.51,Electronics,Online,Not Returned,UPS,Rome,Medium,742.50
2,231932,SKU_1501,Headphones,49,2020-01-01 02:00:00,29.11,50472.0,Germany,0.35,Bank Transfer,23.03,Electronics,Online,Returned,UPS,Berlin,High,-1426.39
3,465838,SKU_1760,Desk Lamp,14,2020-01-01 03:00:00,76.68,96586.0,Netherlands,0.14,paypall,11.08,Accessories,Online,Not Returned,Royal Mail,Rome,Low,1073.52
5,744167,SKU_1006,Office Chair,47,2020-01-01 05:00:00,70.16,53887.0,Sweden,0.48,Credit Card,13.98,Electronics,Online,Not Returned,DHL,London,Medium,3297.52
6,210268,SKU_1087,USB Cable,25,2020-01-01 06:00:00,85.74,46567.0,Belgium,0.15,Bank Transfer,12.92,Stationery,Online,Not Returned,FedEx,Amsterdam,High,2143.50
7,832180,SKU_1597,Notebook,8,2020-01-01 07:00:00,95.65,75098.0,Norway,0.04,Bank Transfer,0.00,Electronics,In-store,Not Returned,Royal Mail,Amsterdam,Low,765.20
8,154886,SKU_1907,Wireless Mouse,19,2020-01-01 08:00:00,98.19,87950.0,Belgium,0.05,paypall,12.56,Apparel,Online,Not Returned,UPS,Berlin,High,1865.61
9,237337,SKU_1866,Headphones,40,2020-01-01 09:00:00,98.17,39718.0,Italy,0.16,Bank Transfer,7.71,Apparel,Online,Not Returned,Royal Mail,London,Low,3926.80
10,621430,SKU_1144,Notebook,49,2020-01-01 10:00:00,87.56,13030.0,United Kingdom,0.19,paypall,0.00,Stationery,In-store,Returned,UPS,Paris,Medium,-4290.44

In [18]:
# Get the number of rows (entries) in the DataFrame
row_count = df.shape[0]

print(f"Number of rows in the cleaned DataFrame: {row_count}")

Number of rows in the cleaned DataFrame: 47293

In [19]:
# Save the cleaned DataFrame to a new CSV file
df.to_csv('cleaned_data.csv', index=False)

print("Cleaned data has been saved to 'cleaned_data.csv'.")

Cleaned data has been saved to 'cleaned_data.csv'.